// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETFrC2yhiWs0KJQg9TPGfVdlEF7yO02w',
    appId: '1:511886037726:web:40cc014acb5c2a4a6f284f',
    messagingSenderId: '511886037726',
    projectId: 'gorilla-beans',
    authDomain: 'gorilla-beans.firebaseapp.com',
    storageBucket: 'gorilla-beans.appspot.com',
    measurementId: 'G-XBLELY4R9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiP2C8blrdS9I-ABE4BkLDvXdwCGOlLmM',
    appId: '1:511886037726:android:c3a27b0534d2ec306f284f',
    messagingSenderId: '511886037726',
    projectId: 'gorilla-beans',
    storageBucket: 'gorilla-beans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaGQqWitUFWjrCLIczEZNFYuqLScB1DU',
    appId: '1:511886037726:ios:8bd34294aa5340f56f284f',
    messagingSenderId: '511886037726',
    projectId: 'gorilla-beans',
    storageBucket: 'gorilla-beans.appspot.com',
    iosClientId: '511886037726-qa16i6ef1lf4tjcvumfcogjb48rnsf71.apps.googleusercontent.com',
    iosBundleId: 'com.instapay.beansInstapay',
  );
}
